Endpoints
laser-ufpb/sac-dm pull request #19
Opened 2023-07-31 23:00 UTC by davigama10

Atualizações nos endpoints

2023-08-02 19:15 UTC, davigama10 commented
Novas funcionalidades de filtros e rotas de post melhoradas.

2023-08-03 12:30 UTC, maelso requested changes

2023-08-03 12:30 UTC, maelso commented on src/server/models/token.py
> +expire_minutes = str(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES"))
Desfazer esta alteração. Isso gerará um erro de "unsupported type" na criação do token

2023-08-03 12:30 UTC, maelso commented on src/server/__pycache__/server.cpython-310.pyc
Remover

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/__pycache__/accelerometer.cpython-310.pyc
Remover

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/__pycache__/device.cpython-310.pyc
Remover

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/__pycache__/sac_dm.cpython-310.pyc
Remover

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/accelerometer.py
> +    db.commit()
Isso pode gerar alguma exceção, proteger com um try e adicionar um except para quando a exceção ocorrer, por exemplo, ocorrendo alguma exceção retornar o código abaixo:

return JSONResponse(         status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            content={"error": "Failed to insert data to the database."})

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/accelerometer.py
> +    else:
Trocar o `else` por `elif(data.datetime_initial and data.datetime_final)`

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/accelerometer.py
> +
Aqui pode existir erro do sqlalchemy e erro de atributo inexistente:
Adicione a verificação se existe o atributo `device_id` em data e adicione um `elif` semelhante ao caso que expliquei acima.

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/sac_dm.py
> +    else:
Mesmo caso do elif

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/sac_dm.py
> +    else:
Mesmo caso do get_accelerometer acima

2023-08-03 12:30 UTC, maelso commented on src/server/controllers/sac_dm.py
> +    else:
try-except em todas as funções que envolvem acesso ao banco

2023-08-11 15:18 UTC, maelso approved these changes

2023-08-11 15:18 UTC, merged